use std::fs::{self, File};
use std::io::Write;
use std::path::Path;
use std::process::Command;

fn sanitize_filename(name: &str) -> String {
    name.replace("/", "_")
        .replace("\\", "_")
        .replace(":", "_")
        .replace("*", "_")
        .replace("?", "_")
        .replace("<", "_")
        .replace(">", "_")
        .replace("|", "_")
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let licenses_dir = Path::new("licenses");
    fs::create_dir_all(licenses_dir)?;

    let output = Command::new("cargo")
        .args(&["license", "--json"])
        .output()?;

    let json_str = String::from_utf8(output.stdout)?;
    let deps: Vec<serde_json::Value> = serde_json::from_str(&json_str)?;

    let mut created_files = Vec::new();

    for dep in deps {
        let name = dep["name"].as_str().unwrap_or("unknown");
        let version = dep["version"].as_str().unwrap_or("unknown");
        let license = dep["license"].as_str().unwrap_or("NO-LICENSE");
        let repo = dep["repository"].as_str().unwrap_or("NO-REPO");
        let authors = dep["authors"].as_str().unwrap_or("N/A");
        let desc = dep["description"].as_str().unwrap_or("N/A");

        let filename = format!("{}-{}.txt", sanitize_filename(name), version);
        let filepath = licenses_dir.join(&filename);

        let mut file = File::create(&filepath)?;
        writeln!(file, "License Information for {} v{}", name, version)?;
        writeln!(file, "{}", "=".repeat(50))?;
        writeln!(file)?;
        writeln!(file, "Crate: {}", name)?;
        writeln!(file, "Version: {}", version)?;
        writeln!(file, "License: {}", license)?;
        writeln!(file, "Repository: {}", repo)?;
        writeln!(file, "Authors: {}", authors)?;
        writeln!(file)?;
        writeln!(file, "Description:")?;
        writeln!(file, "{}", desc)?;
        writeln!(file)?;
        writeln!(file, "{}", "=".repeat(50))?;
        writeln!(file)?;
        writeln!(file, "For the full license text, please refer to:")?;
        writeln!(file, "- The repository URL above")?;
        writeln!(file, "- https://crates.io/crates/{}", name)?;
        writeln!(file, "- The LICENSE or LICENSE-* files in the repository")?;

        created_files.push(filename);
    }

    let mut index_file = File::create(licenses_dir.join("README.txt"))?;
    writeln!(index_file, "License Files Directory")?;
    writeln!(index_file, "=======================")?;
    writeln!(index_file)?;
    writeln!(index_file, "This directory contains license information for all dependencies.")?;
    writeln!(index_file)?;
    writeln!(index_file, "Total dependencies: {}", created_files.len())?;
    writeln!(index_file)?;
    writeln!(index_file, "Files:")?;
    for filename in &created_files {
        writeln!(index_file, "  - {}", filename)?;
    }
    writeln!(index_file)?;
    writeln!(index_file, "Generated by: cargo-license")?;
    writeln!(index_file)?;
    writeln!(index_file, "To regenerate, run: cargo run --bin create_licenses")?;

    println!("Created {} license files in licenses/", created_files.len());
    Ok(())
}
